<?php

function mukurtu_theme_blocks_block_info() {
    $blocks['mukurtu_theme_footer'] = array(
        'info' => t('Mukurtu Theme Default Footer'),
    );

    return $blocks;
}

function mukurtu_theme_blocks_block_view($delta = '') {
    switch($delta) {
    case 'mukurtu_theme_footer':
        return _mukurtu_theme_blocks_footer();
    }
}

function _mukurtu_theme_blocks_footer() {
    //    $block['subject'] = "SUBJECT";
    $block['content'] = '<div class="contact">';

    // Email contact
    $email_us_text = t(theme_get_setting('mukurtu_theme_email_us_message', 'mukurtu'));
    $email_contact_address = theme_get_setting('mukurtu_theme_contact_email', 'mukurtu');
    if($email_contact_address != '') {
        $email_contact_address = l($email_contact_address, 'mailto:' . $email_contact_address);
        if($email_us_text != '') {
            $block['content'] .= "<div class='contactus col-md-4 col-md-push-4 col-sm-6 col-xs-12'><span class='emailicon'>$email_us_text $email_contact_address</span></div>";
        }
    }

    // Twitter
    $twitter_message = theme_get_setting('mukurtu_theme_twitter_message', 'mukurtu');
    $twitter1 = theme_get_setting('mukurtu_theme_twitter1', 'mukurtu');
    $twitter2 = theme_get_setting('mukurtu_theme_twitter2', 'mukurtu');
    $twitter_url = 'https://twitter.com/';
    
    $first_twitter = TRUE;
    foreach(array($twitter1, $twitter2) as $twitter) {
        if($twitter != '') {
            // Create wrapper div
            if($first_twitter) {
                $first_twitter = FALSE;
                $block['content'] .= '<div class="twitter-wrapper col-md-4 col-md-push-4 col-sm-6 col-xs-12">';
                $firstclass =  " twittericon";
            } else {
                $firstclass = "";
                $twitter_message = "";
            }
            $twitter_link = l('@' . $twitter, $twitter_url . $twitter);
            $block['content'] .= "<div class='twitter$firstclass'>$twitter_message $twitter_link</div>";
        }
    }

    // Close twitter div
    if(!$first_twitter) {
        $block['content'] .= '</div>';
    }

    // Close contact div
    $block['content'] .= "</div>";

    // Copyright
    $year = date("Y");   
    $copyright = str_replace('[year]', $year, theme_get_setting('mukurtu_theme_copyright', 'mukurtu'));
    if($copyright != '') {
        $block['content'] .= "<div class='copyright col-md-pull-8 col-md-4 col-xs-12'>$copyright</div>";
    }

    return $block;
}
