<?php
/**
* @file
* Define Mukurtu image carousel display formatter
*
*/

/**
 * Implements hook_field_formatter_info().
 */
function mukurtu_display_formatters_image_carousel_field_formatter_info() {
    return array(
        'mukurtu_image_carousel_formatter' => array(
            'label' => t('Mukurtu Image Carousel'),
            'field types' => array('atom_reference'),
            'settings' => array()
        ),
    );
}

/**
* Implements hook_field_formatter_settings_form().
*/
function mukurtu_display_formatters_image_carousel_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
    $display = $instance['display'][$view_mode];
    $settings = $display['settings'];
    $element = array();
    return $element;
}

/**
* Implements hook_field_formatter_settings_summary().
*/
function mukurtu_display_formatters_image_carousel_field_formatter_settings_summary($field, $instance, $view_mode) {
    $display = $instance['display'][$view_mode];
    $settings = $display['settings'];
    $summary = t('Display Scald atoms in a carousel');
    return $summary;
}

/**
* Implements hook_field_formatter_view().
*/
function mukurtu_display_formatters_image_carousel_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
    $images = array();
    $settings = $display['settings'];

    foreach ($items as $delta => $item) {
        if(isset($item['sid'])) {
            $images[]['row'] = scald_render($item['sid'], 'ma_colorbox');
        }
    }

    $element = array(
        '#theme' => 'owlcarousel',
        '#items' => $images,
        '#settings' => array(
            // The settings group to apply.
            'instance' => 'owlcarousel_settings_mukurtu_single_image',
            // Attributes are rendered via drupal_attributes on the wrapper element.
            'attributes' => array(
                'id' => array(
                    'default' => drupal_html_id('image_carousel_' . $instance['field_id'])
                ),
            )
        )
    );

    return $element;
}