<?php

function license_traditional_license_load($data) {
  $info = explode('/', trim($data['path'], '/'));
  if ($data['host'] == 'localcontexts.org' && $info[0] == 'tk') {
    return array(
      'key' => $info[1],
      'version' => $info[2],
      'uri' => $data['uri'],
      'name' => $data['name'],
      'type' => 'traditional',
    );
  }
}

function license_traditional_build_license_label_uri($uri) {
  $pattern = '/http:\/\/localcontexts.org\/tk\/([a-z]+)\/.*/';
  $letter= preg_match($pattern, $uri, $matches);
  return "https://github.com/kimberlycw/Local-Contexts/raw/master/{$matches[1]}/label_{$matches[1]}.png";
}

function license_traditional_license_display($license, $entity) {
  if ($license['type'] == 'traditional') {
    list ($tk_license_text, $uri) = mukurtu_build_tk_label_text ($entity, $license);
    return license_basic_display($uri, $license['name'], license_traditional_build_license_label_uri($license['uri']), 'Traditional Knowledge Label', $tk_license_text);
  }
}

function license_traditional_license_display_export($license, $entity) {
  if ($license['type'] == 'traditional') {
    $uri_attributes = array();
    return license_basic_display($license['uri'], $license['name'], license_traditional_build_license_label_uri($license['uri']), 'Traditional Knowledge Label', 'hover text');
  }
}

