<?php
/**
 * @file
 * Code for the Mukurtu Person feature.
 */

include_once 'ma_person.features.inc';

/**
 * Implements hook_node_view_alter().
 */
function ma_person_node_view_alter(&$build) {
    // Only display the first media item for the Person type, for the "Person Teaser" display mode
    if($build['#entity_type'] == 'node' && $build['#bundle'] == 'person' && $build['#view_mode'] == 'person_teaser') {
        if(isset($build['field_media_asset'])) {
            $count = 0;
            foreach($build['field_media_asset']['#items'] as $index => $media_item) {
                if($count > 0) {
                    if(isset($build['field_media_asset'][$index])) {
                        unset($build['field_media_asset'][$index]);
                    }
                }
                $count++;
            }
        }
    }
}

/**
 * Implements hook_node_view().
 */
/*
function ma_person_node_view($node, $view_mode, $langcode) {
    if($node->type == 'person' && $view_mode == 'ffull') {

        // We want to build a table of contents for the following:
        // 1. Related People
        // 2. Each paragraph section
        // 3. Content the person is found in
        $items = array();

        // Related People
        if(isset($entity->field_related_people[LANGUAGE_NONE]) && !empty($entity->field_related_people[LANGUAGE_NONE])) {
            $items[] = t("<a href='@url'>Related People</a>", array('@url' => '#related-people'));
        }

        // Paragraph Sections
        if(!empty($entity->field_sections[LANGUAGE_NONE])) {
            foreach($entity->field_sections[LANGUAGE_NONE] as $index => $section) {
                $paragraphs = entity_load('paragraphs_item', array($section['value']));
                $paragraph = $paragraphs[key($paragraphs)];
                $title = isset($paragraph->field_section_title['und'][0]['safe_value']) ? $paragraph->field_section_title['und'][0]['safe_value'] : t('Section ') . ($index + 1);
                $items[] = t("<a href='#section-@num'>@title</a>", array('@num' => $index + 1, '@title' => $title));
            }
        }

        // Found in
        if(!empty($entity->field_node_aggregate[LANGUAGE_NONE])) {
            $items[] = t("<a href='@url'>Referenced Content</a>", array('@url' => '#found-in'));
        }
        

        if(count($items) > 1) {
            $toc = array(
                '#title' => t('Contents'),
                '#prefix' => '<div class="tableofcontents">',
                '#items' => $items,
                '#theme' => 'item_list',
                '#suffix' => '</div>'
            );
            
            print drupal_render($toc);
        }




        
        $node->content['field_toc'] = array(
            '#weight' => 3,
            '#theme' => 'ma_person_toc',
        );
        $node->content['field_toc']['#markup'][0] = drupal_render($toc);
        //        dpm($node);
    }
}
*/
/*function ma_person_field_display_node_alter(&$display, $context) {
    if($context['entity']->type == 'person' && $context['view_mode'] == 'full' ){
        //        dpm($context);
    }
    }*/