; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[] = "admin_menu"
projects[] = "commerce"
projects[] = "ctools"
projects[] = "elements"
projects[] = "entity"
projects[] = "entityreference"
projects[] = "features"
projects[] = "field_collection"
projects[] = "profile2"
projects[] = "references"
projects[] = "views"

projects[cer][download][type] = "git"
projects[cer][download][url] = "http://git.drupal.org/project/cer.git"
projects[cer][download][branch] = "7.x-3.x"
