<?php

/**
 * @file
 * Scald Youtube Installation.
 */

/**
 * Implements hook_install().
 */
function scald_youtube_install() {
  ScaldAtomController::addType('video', 'Video', 'Video');
}

/**
 * Implements hook_uninstall().
 */
function scald_youtube_uninstall() {
  drupal_load('module', 'scald');
  // If Scald is disabled, its classes are not autoloaded.
  module_load_include('inc', 'scald', 'includes/ScaldAtomController');

  ScaldAtomController::removeType('video');
}
