<?php
/**
 * @file
 * Basic functionality for inserting argument values into Views filter settings.
 */

/**
 * Implements hook_views_query_substitutions().
 */
function argfilters_views_query_substitutions() {
  // TODO: Cache this thing, so we don't have reload the view if it is already
  // loaded. Alternatively, make sure that Views does this alreday (which is
  // likely).
  $view = views_get_current_view();
  // Build the array of replacement patterns, but only if there is any arguments
  // set.
  $replacements = array();
  if (is_array($view->argument)) {
    foreach ($view->argument as $index => $argument) {
      // Shift all indeces up one step, to sync with the outward-facing
      // denumeration used in the Views interface.
      if (is_numeric($index)) {
        $newindex = $index + 1;
        $replacements["!$newindex"] = $argument->argument;
        // TODO: Use $view->argument to load the validated title for the argument
        // object, if there is any. For now, we only use the raw input value.
        $replacements["%$newindex"] = $argument->argument;
      }
    }
  }

  return $replacements;
}
