<?php
/**
 * @file
 * Code for the Mukurtu Glossary feature.
 */

include_once 'ma_glossary.features.inc';

function ma_glossary_menu() {
  $items['node/%node/add-term'] = array(
    'title' => 'Add New Glossary Term',
    'page callback' => 'ma_glossary_add_glossary_term',
    'page arguments' => array(1),
    'access callback' => 'ma_glossary_add_glossary_term_check',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 100,
  );

  return $items;
}

function ma_glossary_add_glossary_term($node) {
  drupal_goto ('node/add/glossary-term/' . $node->nid);
}

function ma_glossary_add_glossary_term_check($node) {
  if($node->type == 'glossary') {
    return TRUE;
  }

  return FALSE;
}

function ma_glossary_form_glossary_term_node_form_alter(&$form, &$form_state) {
  if(arg(2) == 'glossary-term') {
    if(arg(3) && $glossary_node = node_load(arg(3))) {
      drupal_set_title(t("Create Glossary Term in ") . $glossary_node->title);
      node_save($glossary_node);
    }
  }
}

function ma_glossary_node_insert($node) {
  if($node->type == 'glossary_term') {
    // Add new glossary term to glossary, if one was specified
    if(arg(3) && $glossary_node = node_load(arg(3))) {
      if($glossary_node->type == 'glossary') {
	$glossary_node->field_glossary_terms[LANGUAGE_NONE][]['target_id'] = $node->nid;
	node_save($glossary_node);
	drupal_goto(drupal_get_path_alias('node/' . $glossary_node->nid));
      }
    }
  }
}

function ma_glossary_field_extra_fields() {
  $extra['node']['glossary_term'] = array('display' => array('found_in_glossary' => array(
					  'label' => t('Found in Glossary'),
					  'description' => t('Which glossary or glossaries the term is found in.'),
					  'weight' => '-5',
					  ),),);

  $extra['node']['glossary_term']['display']['glossary_navigation'] = array(
									    'label' => t('Glossary Navigation Buttons'),
									    'description' => t('Glossary Navigation Buttons'),
									    'weight' => '-10',
									    );
  return $extra;
}


function ma_glossary_node_view($node, $view_mode) {
  if($node->type == 'glossary') {
    if($view_mode == 'full') {
      foreach($node->content['field_glossary_terms']['#items'] as $key => $target_id) {
	$node->content['field_glossary_terms'][$key]['#markup'] = "";
      }
      
      $glossary_content = views_embed_view('mukurtu_glossary', 'page_mukurtu_glossaries', $node->nid);
      $node->content['field_glossary_terms'][0]['#markup'] = $glossary_content;
    }
  } elseif($node->type == 'glossary_term') {
    // Find which glossaries the term belongs to
    $glossaries_found_in = array();
    $glossary_links = "";
    $query = new EntityFieldQuery();
    $result = $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'glossary')
      ->execute();
    $glossary_nodes = node_load_multiple(array_keys($result['node']));
    foreach($glossary_nodes as $glossary) {
      foreach($glossary->field_glossary_terms[LANGUAGE_NONE] as $term) {
	if($term['target_id'] == $node->nid) {
	  $glossaries_found_in[] = $glossary->nid;
	  if(count($glossaries_found_in) > 1) {
	    $glossary_links .= ', ';
	  }
	  //	  $glossary_home_path = url(drupal_get_path_alias('node/' . $glossary->nid));
	  $glossary_home_path = url('glossaries/' . $glossary->nid);
	  $glossary_links .= '<a href="'.$glossary_home_path.'">'. $glossary->title . '</a>';
	}
      }
    }

    // Builds the list of glossaries the term is a member of
    $glossary_label = (count($glossaries_found_in) > 1) ? "glossaries" : "glossary";
    $node->content['found_in_glossary'] = array('#markup' => '<div class="field field-found-in-glossary"><div class=\'label-above\'>Found in ' . $glossary_label . ':</div>' . $glossary_links . '</div>',);

    // If the term is just in a single glossary, build buttons that link to the previous/next terms
    if(count($glossaries_found_in) == 1) {
      $previous = "";
      $next = "";
      foreach($glossary_nodes[$glossaries_found_in[0]]->field_glossary_terms[LANGUAGE_NONE] as $key => $term) {
	if($term['target_id'] == $node->nid) {
	  if(isset($glossary_nodes[$glossaries_found_in[0]]->field_glossary_terms[LANGUAGE_NONE][$key - 1])) {
	    $previous_nid = $glossary_nodes[$glossaries_found_in[0]]->field_glossary_terms[LANGUAGE_NONE][$key - 1]['target_id'];
	    $previous_node = node_load($previous_nid);
	    $previous = '< ' . $previous_node->title . ' (' . $previous_node->field_translation[LANGUAGE_NONE][0]['value'] . ')';
	    $previous_link = url(drupal_get_path_alias('node/' . $previous_nid));
	  }
	  if(isset($glossary_nodes[$glossaries_found_in[0]]->field_glossary_terms[LANGUAGE_NONE][$key + 1])){
	    $next_nid = $glossary_nodes[$glossaries_found_in[0]]->field_glossary_terms[LANGUAGE_NONE][$key + 1]['target_id'];
	    $next_node = node_load($next_nid);
	    $next = $next_node->title . ' (' . $next_node->field_translation[LANGUAGE_NONE][0]['value'] . ') >';
	    $next_link = url(drupal_get_path_alias('node/' . $next_nid));
	  }
	  break;
	}
      }
      $node->content['glossary_navigation'] = array('#markup' => '<div class="row"><div class="col-md-6"><a href="'. $previous_link . '" class="btn">' . $previous . '</a></div><div class="col-md-6"><a href="'.$next_link.'" class="btn">' . $next . '</a></div></div>');
    }
    
    //    $node->content
  }
}

function ma_glossary_views_pre_render(&$view) {
  //  dpm($view);

  if($view->name == 'mukurtu_glossary' && $view->is_attachment == FALSE) {
    if(isset($view->args)) {
      $node = node_load($view->args[0]);
      if($node) {
	//	dpm($node);
  	//$view->set_title($node->field_glossary_source[LANGUAGE_NONE][0]['value']);
	$view->set_title($node->title);
      }
    }
  }
}